/********************************************************************
* C:/Users/Argg/Documents/Neuer Ordner/gitHub/correlations/cBuild/sct_plot/SCT_plotsDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error C:/Users/Argg/Documents/Neuer Ordner/gitHub/correlations/cBuild/sct_plot/SCT_plotsDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevSCT_plotsDict();
extern G__DLLEXPORT void G__set_cpp_environmentSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_tagtableSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_typetableSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_memvarSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_globalSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_memfuncSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setup_funcSCT_plotsDict();
extern G__DLLEXPORT void G__cpp_setupSCT_plotsDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "C:/Users/Argg/Documents/Neuer Ordner/gitHub/correlations/sct_plot/inc/sct_plots.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SCT_plotsDictLN_TClass;
extern G__linked_taginfo G__SCT_plotsDictLN_TBuffer;
extern G__linked_taginfo G__SCT_plotsDictLN_TMemberInspector;
extern G__linked_taginfo G__SCT_plotsDictLN_TString;
extern G__linked_taginfo G__SCT_plotsDictLN_iteratorlErandom_access_iterator_tagcOcharcOlongcOcharmUcOcharaNgR;
extern G__linked_taginfo G__SCT_plotsDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SCT_plotsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SCT_plotsDictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__SCT_plotsDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SCT_plotsDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SCT_plotsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SCT_plotsDictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__SCT_plotsDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__SCT_plotsDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SCT_plotsDictLN_TTree;
extern G__linked_taginfo G__SCT_plotsDictLN_TFile;
extern G__linked_taginfo G__SCT_plotsDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__SCT_plotsDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SCT_plotsDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SCT_plotsDictLN_sct;
extern G__linked_taginfo G__SCT_plotsDictLN_axis_ref;
extern G__linked_taginfo G__SCT_plotsDictLN_S_treeCollection;
extern G__linked_taginfo G__SCT_plotsDictLN_plane_hit;
extern G__linked_taginfo G__SCT_plotsDictLN_S_plane;
extern G__linked_taginfo G__SCT_plotsDictLN_S_plot_def;
extern G__linked_taginfo G__SCT_plotsDictLN_S_plot;
extern G__linked_taginfo G__SCT_plotsDictLN_axis_def;
extern G__linked_taginfo G__SCT_plotsDictLN_S_Axis;
extern G__linked_taginfo G__SCT_plotsDictLN_S_DrawOption;
extern G__linked_taginfo G__SCT_plotsDictLN_S_plot_collection;

/* STUB derived class for protected member access */
